### ISSUE TITLE
Print graphics requests

### ISSUE THREAD

**Issue by jenniferhawes** [postandcourier/schools#22]
On the day 3 read in, let's link our pencil graphic from the print edition that shows how CCSD has the top and bottom schools to this graph:   Last year, 217 public high schools across South Carolina received state rankings. Five of the top 30 and six of the bottom 40 were in Charleston County, more than any other district. Just four of its high schools fell into the middle 147.  And let's link our graphic for print that shows how schools rank (Excellent, Good, At Risk, etc.) in all three tri-county counties to this graph:   Districts in neighboring Berkeley and Dorchester counties have none in the bottom 40. Like most districts across rural South Carolina, they also have limited school choice.

**Comment by jemory** [comment]
Waiting for Brandon since he has all these files.

**Comment by lauragaton** [comment]
>>"On the day 3 read in, let's link our pencil graphic from the print edition that shows how CCSD has the top and bottom schools to this graph: Last year, 217 public high schools across South Carolina received state rankings. Five of the top 30 and six of the bottom 40 were in Charleston County, more than any other district. Just four of its high schools fell into the middle 147."
- We can't really display the graphic within the leadin. @jemory has it placed near the top though.

**Comment by jemory** [comment]
I've incorporated the graphics that I think work best with the narrative flow of the story. A few of the images need to be updated. I'll work with Brandon to see if we can also update the typography on the image to match the web design.
