### ISSUE TITLE
Day 5 Header and subhead should match print

### ISSUE THREAD

**Issue by glennsmith5** [postandcourier/schools#43]
Head: Everything rides on a school's reputation
Subhead: North Charleston High shoulders unfair burden in fight for higher ratings, but a few seniors' triumphs make anything seem possible

**Comment by jemory** [comment]
Page headers are editable just like paragraphs and other items on the page.

**Comment by glennsmith5** [comment]
Doesn't work

**Comment by jemory** [comment]
I think we both just tried to change it at the same time :)

**Comment by lauragaton** [comment]
Done.
