### ISSUE TITLE
When I am editing copy, my cursor keeps jumping back to the top of the page when I click off whatever I was working on.

### ISSUE THREAD

**Issue by jenniferhawes** [postandcourier/schools#46]

**Comment by lauragaton** [comment]
Same here.

**Comment by jemory** [comment]
Appears to be a bug in Chrome related to my earlier change which preserves scroll position when you use back/forward buttons. Until I can look into this issue, I recommend editing the page in Firefox.

**Comment by jemory** [comment]
Fixed in commit 16eaa5d
